export const GET_CHARACTERS_STARTED : string = "@/GET/CHARACTERS/STARTED";
export const GET_CHARACTERS_SUCCESS : string = "@/GET/CHARACTERS/SUCCESS";
export const GET_CHARACTERS_FAILED : string = "@/GET/CHARACTERS/FAILED";